
spring:
  application:
    name: proFile
  datasource:
    url: jdbc:postgresql://localhost:5432/proFile
    username: postgres
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: ${GEMINI_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-2.5-flash


jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000




